all:
  children:
    k8s_cluster:
      children:
        masters:
          hosts:
            master:
              ansible_host: 192.168.56.10
              node_ip: 192.168.56.10
              ansible_user: vagrant
              ansible_ssh_private_key_file: ../infrastructure/vagrant/.vagrant/machines/master/virtualbox/private_key

        workers:
          hosts:
            worker1:
              ansible_host: 192.168.56.11
              node_ip: 192.168.56.11
              ansible_user: vagrant
              ansible_ssh_private_key_file: ../infrastructure/vagrant/.vagrant/machines/worker1/virtualbox/private_key

            worker2:
              ansible_host: 192.168.56.12
              node_ip: 192.168.56.12
              ansible_user: vagrant
              ansible_ssh_private_key_file: ../infrastructure/vagrant/.vagrant/machines/worker2/virtualbox/private_key
              
    jenkins_server:
      hosts:
        jenkins:
          ansible_host: 192.168.56.10 
          ansible_user: vagrant
          ansible_ssh_private_key_file: ../infrastructure/vagrant/.vagrant/machines/master/virtualbox/private_key
          ansible_python_interpreter: /usr/bin/python3

    sqlserver:
      hosts:
        sql-server:
          ansible_host: 192.168.56.10  
          ansible_user: vagrant
          ansible_ssh_private_key_file: ../infrastructure/vagrant/.vagrant/machines/master/virtualbox/private_key
          ansible_python_interpreter: /usr/bin/python3

  vars:
    k8s_version: "1.28"
    pod_network_cidr: "192.168.0.0/16"
    service_cidr: "10.96.0.0/12"
    kubernetes_repo_key: "https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key"
    kubernetes_repo: "deb https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
